# Generated by Django 4.1.6 on 2023-02-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_alter_produto_preco_marketing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='descricao_curta',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='descricao_longa',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='preco_marketing_promocional',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='variacao',
            name='preco_promocional',
        ),
        migrations.AddField(
            model_name='produto',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
