# Generated by Django 4.1.6 on 2023-02-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_pedido_qtd_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='frete',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pedido',
            name='subtotal',
            field=models.FloatField(default=0),
        ),
    ]
